# Generated by Django 4.1.2 on 2023-02-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Project',
        ),
    ]
