# Generated by Django 4.1.2 on 2023-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='main.project'),
        ),
    ]
