# Generated by Django 4.1.2 on 2023-02-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_assigned_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_projects',
        ),
    ]
