# Generated by Django 4.1.2 on 2023-02-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
