# Generated by Django 4.1.2 on 2023-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_timespent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
