# Generated by Django 4.1.2 on 2023-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timespent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timespent',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Студент', 'Студент')], default='', max_length=20, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
        migrations.DeleteModel(
            name='TimeSpent',
        ),
    ]
