# Generated by Django 4.1.2 on 2023-10-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_question_test_usertestresult_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='block_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
