# Generated by Django 4.1.2 on 2023-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_test_questions_question_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='block_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
