# Generated by Django 4.1.2 on 2023-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_usertestresult_block_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestresult',
            name='block_name',
        ),
        migrations.AlterField(
            model_name='test',
            name='block_name',
            field=models.CharField(choices=[('TRIAL', 'Пробный'), ('LOW', 'Низкий'), ('BASE', 'Базовый'), ('HIGH', 'Высокий'), ('FINAL', 'Итоговый')], max_length=50),
        ),
    ]
