# Generated by Django 4.1.2 on 2023-10-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_test_block_name_test_block_test_is_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='block',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_final',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='usertestresult',
            unique_together={('user', 'test')},
        ),
        migrations.RemoveField(
            model_name='usertestresult',
            name='date_completed',
        ),
    ]
