# Generated by Django 4.1.2 on 2023-10-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_testresult_alter_usertestresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_block',
            field=models.CharField(blank=True, choices=[('L1', 'Низкий 1'), ('L2', 'Низкий 2'), ('M1', 'Средний 1'), ('M2', 'Средний 2'), ('H1', 'Высокий 1'), ('H2', 'Высокий 2'), ('', 'None')], max_length=2, null=True, verbose_name='Блок сложности'),
        ),
    ]
