# Generated by Django 4.1.2 on 2023-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
