# Generated by Django 4.1.2 on 2023-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_text',
            field=models.TextField(blank=True, null=True, verbose_name='Правильный текстовый ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TE', 'Text Entry')], default='MC', max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
