# Generated by Django 4.1.2 on 2023-10-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_answer_correct_text_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct_text',
        ),
    ]
