# Generated by Django 4.1.2 on 2023-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_answer_correct_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'Text Field')], default='MC', max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
