# Generated by Django 4.1.2 on 2023-10-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_disciplin'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='disciplin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.disciplin'),
            preserve_default=False,
        ),
    ]
