# Generated by Django 4.1.2 on 2023-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_question_disciplin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.disciplin'),
        ),
    ]
