# Generated by Django 4.1.2 on 2023-10-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_topic_remove_subsection_section_delete_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='disciplin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.disciplin'),
            preserve_default=False,
        ),
    ]
