# Generated by Django 4.1.2 on 2023-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_question_image_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Ответы с галочкой'), ('TF', 'Текстовый ответ')], default='MC', max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
