# Generated by Django 4.1.2 on 2023-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_topic_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discipline_images/'),
        ),
    ]
