# Generated by Django 4.1.2 on 2023-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_disciplin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Преподаватель', 'Преподаватель'), ('Студент', 'Студент')], default='Студент', max_length=20, verbose_name='Должность'),
        ),
    ]
