# Generated by Django 4.1.2 on 2023-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='difficulty_block',
            field=models.CharField(blank=True, choices=[('L1', 'Низкий 1'), ('L2', 'Низкий 2'), ('M1', 'Средний 1'), ('M2', 'Средний 2'), ('H1', 'Высокий 1'), ('H2', 'Высокий 2'), ('NN', 'Вводный')], default='NN', max_length=2, verbose_name='Блок сложности'),
        ),
    ]
