# Generated by Django 4.1.2 on 2023-11-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_user_difficulty_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
