# Generated by Django 4.1.2 on 2023-11-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('disciplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.disciplin')),
            ],
        ),
    ]
