# Generated by Django 4.1.2 on 2023-11-06 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Файл лекции'),
        ),
    ]
