# Generated by Django 4.1.2 on 2023-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_topic_content_topic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='incorrect_answers',
            field=models.JSONField(default=list),
        ),
    ]
