# Generated by Django 4.1.2 on 2023-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_quizresult_incorrect_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalquizsresult',
            name='incorrect_answers',
            field=models.JSONField(default=list),
        ),
    ]
