# Generated by Django 4.1.2 on 2023-11-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_finalquizsresult_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalquizsresult',
            name='correct_answers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finalquizsresult',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finalquizsresult',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
