# Generated by Django 4.1.2 on 2023-11-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_finalquizsresult_correct_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalquizsresult',
            name='start_time',
        ),
    ]
