# Generated by Django 4.1.2 on 2023-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_finalquizsresult_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file_downloaded',
            field=models.BooleanField(default=False, verbose_name='Файл скачан'),
        ),
    ]
