# Generated by Django 4.1.2 on 2023-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_topic_file_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_attempts',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
