# Generated by Django 4.1.2 on 2023-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_finalquizsresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalquizsresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
