# Generated by Django 4.1.2 on 2023-11-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_userdisciplinedifficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplin',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='group_for_USER',
            field=models.CharField(default=111, max_length=4, validators=[django.core.validators.RegexValidator(message='Формат группы должен быть: одна заглавная буква и три цифры (например, Y033)', regex='^[A-Z][0-9]{3}$')], verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
