# Generated by Django 4.1.2 on 2023-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_remove_disciplin_groups_user_group_for_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_for_USER',
            field=models.CharField(max_length=4, verbose_name='Группа'),
        ),
    ]
