# Generated by Django 4.1.2 on 2023-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_user_is_exam_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_exam_disciplin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
