# Generated by Django 4.1.2 on 2023-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_user_current_exam_disciplin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_exam_in_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
