# Generated by Django 4.1.2 on 2023-11-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_user_is_exam_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_exam_disciplin_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_exam_in_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
